CREATE DATABASE OnlineShop

USE OnlineShop

CREATE TABLE [ItemTypes](
	[ItemTypeID] INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(10) NOT NULL
) 

CREATE TABLE [Cities](
	[CityID] INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE [Items](
	[ItemID] INT PRIMARY KEY IDENTITY(10, 1),
	[Name] VARCHAR(50) NOT NULL,
	[ItemTypeID] INT FOREIGN KEY REFERENCES[ItemTypes](ItemTypeID)
)

CREATE TABLE [Customers](
	[CustomerID] INT PRIMARY KEY IDENTITY(10, 1),
	[Name] VARCHAR(50) NOT NULL,
	[Birthday] DATE NOT NULL,
	[CityID] INT FOREIGN KEY REFERENCES[Cities](CityID)
)

CREATE TABLE [Orders](
	[OrderID] INT PRIMARY KEY IDENTITY(100, 1),
	[CustomerID] INT FOREIGN KEY REFERENCES[Customers](CustomerID)
)

CREATE TABLE [OrderItems](
	[OrderID] INT FOREIGN KEY REFERENCES[Orders](OrderID),
	[ItemID] INT FOREIGN KEY REFERENCES[Items](ItemID),
	CONSTRAINT PK_OrderItems PRIMARY KEY(OrderID, ItemID)
)